# Generated by Django 6.0.3 on 2026-03-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="native_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.language",
            ),
        ),
    ]
