# Generated by Django 6.0.3 on 2026-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kanjiword",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="kanjiword",
            constraint=models.UniqueConstraint(
                fields=("word", "position"), name="unique_word_position"
            ),
        ),
    ]
