# Generated by Django 6.0.3 on 2026-03-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_userprofile_native_language"),
        ("reading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passage",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.language",
            ),
        ),
    ]
