# Generated by Django 6.0.3 on 2026-04-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_userprofile_native_language"),
        ("reading", "0002_passage_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paragraph_images",
                to="home.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="passage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passage_covers",
                to="home.mediafile",
            ),
        ),
    ]
