# Generated by Django 6.0.3 on 2026-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="back_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="front_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
