# Generated by Django 6.0.3 on 2026-03-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0004_alter_deck_estimated_level_alter_deck_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deck",
            options={"ordering": ["-created_at"]},
        ),
    ]
